### ISSUE TITLE
Empty document failing on PDF generation

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ribose#117]
[INFO] XSL-FO file preparation...
       Transforming... Ιουν 22, 2021 12:49:28 ΠΜ org.apache.fop.apps.FopConfParser configure
       INFO: Default page-height set to: 11.00in
       Ιουν 22, 2021 12:49:28 ΠΜ org.apache.fop.apps.FopConfParser configure
       INFO: Default page-width set to: 8.50in
       Ιουν 22, 2021 12:49:29 ΠΜ org.apache.fop.events.LoggingEventListener processEvent
       WARNING: Font "STIX Two Math,normal,300" not found. Substituting with "STIX Two Math,normal,400".
       Ιουν 22, 2021 12:49:29 ΠΜ org.apache.fop.events.LoggingEventListener processEvent
       WARNING: Content overflows the viewport of an fo:block-container in block-progression direction by 11189 millipoints. (See position 1:754294)
       Ιουν 22, 2021 12:49:30 ΠΜ org.apache.fop.events.LoggingEventListener processEvent
       INFO: Rendered page #1.
       javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: "fo:block-container" is missing child elements. Required content model: marker* (%block;)+ (See position 1:2029038)
       	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
       	at com.metanorma.fop.mn2pdf.runFOP(mn2pdf.java:311)
       	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:244)
       	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:528)
       Caused by: org.apache.fop.fo.ValidationException: "fo:block-container" is missing child elements. Required content model: marker* (%block;)+ (See position 1:2029038)
       	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
       	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
       	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
       	at com.sun.proxy.$Proxy12.missingChildElement(Unknown Source)
       	at org.apache.fop.fo.FONode.missingChildElementError(FONode.java:608)
       	at org.apache.fop.fo.flow.BlockContainer.endOfNode(BlockContainer.java:144)
       	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
       	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
       	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:184)
       	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:352)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
       	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:113)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:507)
       	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:867)
       	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:796)
       	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:142)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
       	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
       	... 3 more
       ---------
       org.apache.fop.fo.ValidationException: "fo:block-container" is missing child elements. Required content model: marker* (%block;)+ (See position 1:2029038)
       	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
       	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
       	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
       	at com.sun.proxy.$Proxy12.missingChildElement(Unknown Source)
       	at org.apache.fop.fo.FONode.missingChildElementError(FONode.java:608)
       	at org.apache.fop.fo.flow.BlockContainer.endOfNode(BlockContainer.java:144)
       	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
       	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
       	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:184)
       	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:352)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
       	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:113)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:507)
       	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:867)
       	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:796)
       	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:142)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
       	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
       	at com.metanorma.fop.mn2pdf.runFOP(mn2pdf.java:311)
       	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:244)
       	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:528)
     # /Users/nickn/.rvm/gems/ruby-2.7.2/gems/mn2pdf-1.32/lib/mn2pdf.rb:40:in `convert'
     # /Users/nickn/.rvm/gems/ruby-2.7.2/gems/metanorma-1.3.4/lib/metanorma/output/xslfo.rb:10:in `convert'
     # /Users/nickn/.rvm/gems/ruby-2.7.2/gems/isodoc-1.6.7.1/lib/isodoc/xslfo_convert.rb:36:in `convert'
     # /Users/nickn/.rvm/gems/ruby-2.7.2/gems/metanorma-generic-1.10.1/lib/asciidoctor/generic/converter.rb:82:in `outputs'
     # /Users/nickn/.rvm/gems/ruby-2.7.2/gems/metanorma-standoc-1.9.4/lib/asciidoctor/standoc/base.rb:165:in `document'
     # /Users/nickn/.rvm/gems/ruby-2.7.2/gems/metanorma-generic-1.10.1/lib/asciidoctor/generic/converter.rb:72:in `document'
     # /Users/nickn/.rvm/gems/ruby-2.7.2/gems/metanorma-standoc-1.9.4/lib/asciidoctor/standoc/utils.rb:14:in `convert'
     # /Users/nickn/.rvm/gems/ruby-2.7.2/gems/asciidoctor-2.0.15/lib/asciidoctor/document.rb:944:in `convert'
     # /Users/nickn/.rvm/gems/ruby-2.7.2/gems/asciidoctor-2.0.15/lib/asciidoctor/convert.rb:119:in `convert'
     # ./spec/asciidoctor/base_spec.rb:44:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:33:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:33:in `chdir'
     # ./spec/spec_helper.rb:33:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:32:in `block (2 levels) in <top (required)>'

**Comment by Intelligent2013** [comment]
Done.
